### ISSUE TITLE
400KB Vim .swp file is served on home page

### ISSUE THREAD

**Issue by waf** [phoenixframework/phoenix_site#26]
On the home page of http://phoenixframework.org/ there is a 400KB file called `/assets/css/.base.css.swp` being served. It looks like a Vim .swp file (second row):

![image](https://user-images.githubusercontent.com/97195/37567392-df75ec2e-2af8-11e8-9e22-3e623273b9d1.png)

It's referenced in the index.html (line 19):

![image](https://user-images.githubusercontent.com/97195/37567394-fceefcb4-2af8-11e8-85a8-e0790864501a.png)

I hunted around in the repository to see if I could fix it myself, but I don't see it referenced anywhere -- maybe it's an artifact from the build process of the previous deploy?

**Comment by Gazler** [comment]
Well that was silly! I've republished to get rid of it. Thanks for raising it.
