### ISSUE TITLE
phoenix 1.4 upgrade guide missing

### ISSUE THREAD

**Issue by oshanz** [phoenixframework/phoenix_site#42]
There is a great [gist post](https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e) created by @chrismccord. shall we get that into here? I'd love to help.

**Comment by Gazler** [comment]
I believe https://github.com/phoenixframework/phoenix_site/pull/41 solves it, I'll merge it now.

**Comment by Gazler** [comment]
Actually, that is just the link to the release announcement. Please do copy the gist contents over here. You can use a previous version for reference https://github.com/phoenixframework/phoenix_site/blob/master/posts/blog--upgrading-from-120-to-130.markdown

**Comment by Gazler** [comment]
Closed via #43 https://phoenixframework.org/blog/upgrading-from-13x-to-140
