### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by lau** [phoenixframework/phoenix_site#47]
I would expect the site to load nicely when visiting https://www.phoenixframework.org/
Instead I get a warning:

> Firefox detected a potential security threat and did not continue to www.phoenixframework.org. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

The error appears on https://www.phoenixframework.org/ (with www) in both Safari and Firefox. Without www the site works fine.

**Comment by nickjj** [comment]
I'm getting this too in Chrome.

If you inspect the certificate it only has `DNS Name=phoenixframework.org` set in the SAN. You would need to also generate a certificate for `www.phoenixframework.org`.

**Comment by lau** [comment]
It looks like it's fixed now 👍
